version: '3'

services:
  nodeapp:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: node-docker
    container_name: nodeapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}" #usa por defecto el .env
    # working_dir: /var/www/pokedex
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
    # volumes:
    #   - ./:/var/www/pokedex

  db:
    image: mongo:5
    container_name: mongo-node
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: onlinemarket
    #Esto mantiene la base de datos cada que levantemos el contenedor
    #volumes:
    #  - ./mongo:/data/db

#docker-compose -f docker-compose.prod.yaml --env-file .env.prod up --build
#docker-compose -f docker-compose.prod.yaml --env-file .env.prod up