
version: '3'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_DATABASE: onlinemarket
    volumes:
      - ./mongo:/data/db

#Levantarlo: docker-compose up -d